# Generated by Django 4.1.5 on 2023-01-13 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('correo', models.EmailField(max_length=254, verbose_name='Email')),
                ('pais', models.CharField(max_length=100, verbose_name='País')),
                ('ci', models.CharField(max_length=11, verbose_name='Carnet de Identidad')),
                ('fecha_entrada', models.CharField(max_length=100, verbose_name='Fecha de Entrada')),
                ('fecha_salida', models.CharField(max_length=100, verbose_name='Fecha de Salida')),
                ('codigo', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reservación',
                'verbose_name_plural': 'Reservaciones',
            },
        ),
    ]
