# Generated by Django 4.1.5 on 2023-01-15 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
        ('reservacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='hotel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel'),
            preserve_default=False,
        ),
    ]
